osx_image: xcode9.3
language: objective-c
jobs:
  include:
    - stage: Testing
      before_install:
        - gem install cocoapods
      script: 
        - cd Example
        - pod install
        - xcodebuild test -workspace RxRetroSwift.xcworkspace -scheme RxRetroSwift-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' -quiet
    - stage: Swift Package Manager
      script:
        - swift build
    - stage: deploying to cocoapods
      before_install:
        - echo $TRAVIS_TAG
        - export RXRETROFIT_VERSION=$TRAVIS_TAG
        - gem install cocoapods
      script:
        - pod lib lint --allow-warnings
        - pod trunk push
      if: tag IS present
